# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46a5831b20ed785649bd3d9373a925039c2729f8f6de87e52c0c8f3df3572edc1dd92c54f9c5e44a6f8c95d97b61d3b79e7eece5ab7293b260de29ad010185d2

test:
  secret_key_base: 2449281fc3987fa906adcb7dd76f628db49337da721ab35c3fb1e8998bb9288c1783c01b3913318938a52b143bc79e276600c22263d1cc33abe365275ee850fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
